web:
  build: web/
  env_file: /tmp/triggeriq.env
  ports:
    - "80:5000"
  restart: always
  links:
    - redis
    - rethinkdb_tunnel
changefeed:
  build: changefeed/
  env_file: /tmp/triggeriq.env
  restart: always
  links:
    - rethinkdb_tunnel
    - redis
clock:
  build: clock/
  env_file: /tmp/triggeriq.env
  restart: always
  links:
    - redis
    - rethinkdb_tunnel
worker:
  build: worker/
  env_file: /tmp/triggeriq.env
  restart: always
  links:
    - rethinkdb_tunnel
    - redis
rq_dashboard:
  build: rq_dashboard/
  env_file: /tmp/triggeriq.env
  ports:
    - "9181:9181"
  restart: always
  links:
    - rethinkdb_tunnel
    - redis
splash:
  image: scrapinghub/splash
  env_file: /tmp/triggeriq.env
  restart: always
  ports:
    - "8950:8050"
rethinkdb_tunnel:
  build: rethinkdb_tunnel/
  env_file: /tmp/triggeriq.env
  restart: always
  ports:
    - "28015"
redis:
  image: redis
  restart: always
